name: stream_mixin
description: A simple mixin for adding a stream behaviour to any class object
version: 1.0.2
homepage: https://github.com/arnold-parge/stream_mixin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: