name: stream_mixin
description: A simple mixin for adding a stream behaviour to any class object
version: 2.0.0
homepage: https://github.com/arnold-parge/stream_mixin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: